---
title: "Prediction"
author: "James Barbour"
date: "3/10/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(MASS)
```


This lab is not nearly as good as it should be. Have been dealing with family issues that became a major distraction over the last month. Hopefully future labs won't suffer so much.

```{r}
# data from 2011
hour <- read_csv('https://raw.githubusercontent.com/idc9/stor390/master/data/bikes_2011.csv')

# x data from 2012
hour12_x <- read_csv('https://raw.githubusercontent.com/idc9/stor390/master/data/bikes_12_x.csv')

# set categorical variables to factors
hour <- hour %>% 
  dplyr::select(dteday, season, yr, mnth, hr, holiday, weekday, workingday, weathersit, atemp, hum, windspeed, cnt) %>%
  mutate(workingday=factor(workingday),
         weathersit=factor(weathersit),
         weekday=factor(weekday))

# set categorical variables to factors
hour12_x <- hour12_x %>% 
  dplyr::select(dteday, season, yr, mnth, hr, holiday, weekday, workingday, weathersit, temp, atemp, hum, windspeed) %>%
  mutate(workingday=factor(workingday),
         weathersit=factor(weathersit),
         weekday=factor(weekday))
```

```{r}
summary(hour)

# plot weather vs count
ggplot(hour, mapping = aes(x = weathersit, y = cnt)) + 
  geom_jitter()
# As expected, as weather conditions worsen, ridership decreases.
# hour
ggplot(hour, mapping = aes(x = hr, y = cnt)) + 
  geom_jitter()
# day
ggplot(hour, mapping = aes(x = weekday, y = cnt, color = workingday)) + 
  geom_jitter()
# month
ggplot(hour, mapping = aes(x = mnth, y = cnt)) + 
  geom_jitter()
# season, odd season defs
ggplot(hour, mapping = aes(x = season, y = cnt)) + 
  geom_jitter()
# humidity
ggplot(hour, mapping = aes(x = hum, y = cnt)) + 
  geom_point()
# windspeed
ggplot(hour, mapping = aes(x = windspeed, y = cnt)) + 
  geom_jitter()
# tmp
ggplot(hour, mapping = aes(x = atemp, y = cnt)) + 
  geom_jitter()
# humidity
ggplot(hour, mapping = aes(x = hum, y = cnt)) + 
  geom_point()
# holiday vs ridership
ggplot(hour, mapping = aes(x = holiday, y = cnt)) + 
  geom_jitter()
```

```{r}
# get test/train samples
n <- dim(hour)[1]
n_tr <- floor(n * .8)
tr_indices <- sample(x=1:n, size=n_tr, replace=FALSE)
train <- hour[tr_indices, ]
test <- hour[-tr_indices, ]
```

```{r}
# Try a basic linear model
ggplot(hour) +
    geom_point(aes(x=hr, y=cnt)) +
    geom_smooth(aes(x=hr, y=cnt), color='red', method=lm, se=FALSE)

# no good, we can do better
```

```{r}
# test each combination of predictors, pick best
model <- lm(cnt ~ ., train)
model_test <- stepAIC(model, direction = 'both')
model_test$anova
```

```{r, eval=FALSE}
# this took way too long and eventually crashed R. oops. Let's not use this.
hour <- hour %>%
  dplyr::select(season, mnth, hr, holiday, weathersit, atemp, hum, windspeed, cnt)
# found best combination of predictors for test data, try two-interactions
model <- lm(cnt ~ .*., train)
model_test <- stepAIC(model, direction = 'both')
model_test$anova
```

```{r}
# found best combination of predictors, make model and test
model <- lm(cnt ~ season + mnth + hr + holiday + weathersit + atemp + hum + windspeed, train)

test_results <- test %>% 
  mutate(cnt_pred = predict(model, newdata=test))

summary(test_results)

ggplot(test_results) + 
  geom_point(aes(x=hr, y=cnt)) +
  geom_point(aes(x=hr+.5, y=cnt_pred), color='red')

hour12_x <- hour12_x %>% 
            mutate(cnt_pred=predict(model, newdata = hour12_x))

write_csv(hour12_x, 'bike_predictions_2012_idcarm.csv')

```